server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userportalappdb
    username: user
    password: letmein

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true